# Generated by Django 5.2.7 on 2025-12-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField()),
                ('name', models.CharField(max_length=42)),
                ('url', models.URLField()),
                ('archive', models.FileField(upload_to='downloads/')),
                ('type', models.CharField(choices=[('Video', 'Video'), ('Archive', 'Archive'), ('Generic', 'Generic')])),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
