# Generated by Django 5.2.7 on 2025-12-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='archive',
            field=models.FileField(blank=True, null=True, upload_to='downloads/'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='type',
            field=models.CharField(blank=True, choices=[('Video', 'Video'), ('Archive', 'Archive'), ('Generic', 'Generic')], null=True),
        ),
    ]
