# Generated by Django 5.2.7 on 2025-12-08 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0002_alter_archive_archive_alter_archive_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='archive',
        ),
    ]
