# Generated by Django 5.2.7 on 2025-12-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0003_remove_archive_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='archive',
            field=models.FileField(blank=True, null=True, upload_to='downloads/'),
        ),
    ]
