# Generated by Django 5.2.7 on 2025-12-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0005_alter_archive_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='type',
            field=models.CharField(blank=True, choices=[('Video', 'Video'), ('Archive', 'Archive'), ('Generic', 'Generic')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
