# Generated by Django 5.2.7 on 2026-02-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0006_alter_archive_type_alter_archive_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archive',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='archive',
            name='status',
            field=models.CharField(choices=[('Falha', 'Falha'), ('Pendente', 'Pendente'), ('Concluído', 'Concluido')], default='Concluido', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archive',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
