# Generated by Django 5.2.7 on 2026-02-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0007_rename_date_archive_created_at_archive_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='status',
            field=models.CharField(blank=True, choices=[('Falha', 'Falha'), ('Pendente', 'Pendente'), ('Concluído', 'Concluido')], max_length=10, null=True),
        ),
    ]
